config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "kaigos/top" => "kaigos#top"
  get "quizs/index" => "quizs#index"


  resources :kaigos
  resources :hello

  root "hello#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def index
    end
end

app/controllers/kaigos_controller.rb
class KaigosController < ApplicationController
    def index 
    end    
end

app/controllers/quizs_controller.rb
class QuizsController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/kaigos_helper.rb
module KaigosHelper
end

app/helpers/quizs_helper.rb
module QuizsHelper
end

app/views/hello/index.html.erb
<!DOCTYPE html> <!--この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
    <head><!--ページに表示されない情報(サイトの裏側の設定)-->
        <meta charset="utf-8">

    </head>

    <body class="hello_all">

    <div class="snow">●</div>
    <div class="snow snow2nd">●</div>



        <div class="first-block">

        <h3></h3>
        <h3></h3>
        <h3></h3>
        <h3></h3>
        <h3></h3>
        <h3></h3>
        <h3></h3>
        </div>


        <div class="second-block">
        <h5>介護施設選びにお困りのあなたへ</h5>
        <p style="margin-bottom:1.5em;"></p>
       
        <p>介護施設診断サイト　かめりあ　へようこそ！</p>
        <p></p>
        <p>このWebサイトでは最大6問のシンプルな2択の質問お答えいただくことで、多岐にわたる介護施設の中から最適な施設の診断を行っております!</p>
        <p></p>
        <p>一般的な介護サイトでは、ふまえるべき情報量が多く選びきれない...と思った経験のある方もいらっしゃるのではないでしょうか。</p>
        <p></p>
       <p>この診断では自身やご家族の方にとって最適な施設形態が分かるとともに、自分がどんな条件を重要視しているかも明確になると考えています！</p>
        <p></p>
        <p>この診断を通して、ある程度施設の形態を絞った上で入居したいと思える施設探しに役立てて頂けたら嬉しいです！</p>
        <p></p>
        <p>また、このWebサイトでは認知症予防に役立つちょっとしたクイズもご用意してますので、ぜひ挑戦してみてください!</p>

        </div>

      <div class="third_forth">
        <div class="third-block">
           <div class="ttl_kana1">
           ろ<br>
           う<br>
           じ<br>
           ん<br>
           ホ<br>
           ー<br>
           ム<br>
           を<br>
           し<br>
           ん<br>
           だ<br>
           ん<br>
           </div>
           <%= link_to kaigos_path do %>
            <div class="header_menu_top"></div>
          <% end %>
           <p class="ttl_1"> 
           老<br>
           人<br>
           ホ<br>
           ー<br>
           ム<br>
           を<br>
           診<br>
           断<br>
            </p>
         </div> 

        <div class="forth-block">  
        <div class="ttl_kana2">
        に<br>
        ん<br>
        ち<br>
        し<br>
        ょ<br>
        う<br>
        よ<br>
        ぼ<br>
        う<br>
        く<br>
        い<br>
        ず<br>
        </div>
         <%= link_to quizs_index_path do %>
           <div class="header_menu_top2">
           </div>
         <% end %>
         <div class="desc2">
           <p class="ttl_2"> 
           認<br>
           知<br>
           症<br>
           予<br>
           防<br>
           ク<br>
           イ<br>
           ズ<br>
           </p>
         </div>
        </div>
      </div> 


       
      <footer>
        <p>Copyright © Camellia All Rights Reserved.</p>
      </footer>
    </body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Camellia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <div class="header1">
    <%= link_to hello_index_path do %>
      <div class="header_menu_top3">
      </div>
    <% end %>
    <div class="header-list">
      <ul>
      <%= link_to '老人ホームを診断', :controller => "kaigos", :action => "index" %>
      </ul>
      <li>
      <%= link_to '認知症予防クイズ', :controller => "quizs", :action => "index" %>
      </li>

    </div>
    </div>
    </header>
    

    <main>
      <%= yield %>
    </main>
  </body>
</html>